---
# travis file
language: python
python: "2.7"
notifications:
  email: false

before_install:
  # update the system before running
  - sudo apt-get update -qq

  # add ansible.cfg to pick up roles path.
  - echo -e "[defaults]\nroles_path = ../wireshark_challenge/roles" > ansible.cfg

install:
  # install Ansible from pip.
  - pip install ansible

script:
  # perform syntax check
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # perform playbook check
  - ansible-playbook -i tests/inventory tests/test.yml -e "dhparam_size=1024"
